/* Scuffed OS — Lucide icon wrapper.
   The prototype referenced Lucide icons by kebab-case string name (e.g.
   <Icon name="circle-check-big" />). We keep that ergonomic API but back it with
   the `lucide-react` package: an explicit name→component map so every icon is
   statically imported (tree-shaken, no runtime/lazy flash). Sizing/coloring is
   driven by kit.css (`.parent svg { width: … }`, `color: …` via currentColor),
   exactly as in the design system. */
import {
  Activity,
  AlarmClock,
  AlertTriangle,
  AlignLeft,
  Apple,
  Archive,
  ArrowDownLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  Bell,
  Bike,
  BookOpen,
  Brain,
  Cake,
  Calendar,
  CalendarDays,
  ChartLine,
  Check,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  Clock,
  CornerDownLeft,
  Droplet,
  Dumbbell,
  Egg,
  File,
  FileText,
  Flag,
  Flame,
  Flower2,
  Folder,
  Footprints,
  Forward,
  GraduationCap,
  Heart,
  House,
  Inbox,
  LayoutDashboard,
  Lightbulb,
  ListChecks,
  Mail,
  MapPin,
  Mic,
  Moon,
  Paperclip,
  PartyPopper,
  PenLine,
  Plus,
  RefreshCw,
  Repeat,
  Reply,
  Sandwich,
  Search,
  Send,
  Settings,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  Star,
  Table,
  Tag,
  Trash2,
  TrendingUp,
  Unplug,
  Upload,
  Users,
  Utensils,
  Video,
  Wallet,
  Waves,
  Wifi,
  Wind,
  X,
  Zap,
} from 'lucide-react'

const ICONS = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  'alert-triangle': AlertTriangle,
  'align-left': AlignLeft,
  apple: Apple,
  archive: Archive,
  'arrow-down-left': ArrowDownLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'audio-lines': AudioLines,
  bell: Bell,
  bike: Bike,
  'book-open': BookOpen,
  brain: Brain,
  cake: Cake,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'chart-line': ChartLine,
  check: Check,
  'check-check': CheckCheck,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-check-big': CircleCheckBig,
  clock: Clock,
  'corner-down-left': CornerDownLeft,
  droplet: Droplet,
  dumbbell: Dumbbell,
  egg: Egg,
  file: File,
  'file-text': FileText,
  flag: Flag,
  flame: Flame,
  'flower-2': Flower2,
  folder: Folder,
  footprints: Footprints,
  forward: Forward,
  'graduation-cap': GraduationCap,
  heart: Heart,
  house: House,
  inbox: Inbox,
  'layout-dashboard': LayoutDashboard,
  lightbulb: Lightbulb,
  'list-checks': ListChecks,
  mail: Mail,
  'map-pin': MapPin,
  mic: Mic,
  moon: Moon,
  paperclip: Paperclip,
  'party-popper': PartyPopper,
  'pen-line': PenLine,
  plus: Plus,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  reply: Reply,
  sandwich: Sandwich,
  search: Search,
  send: Send,
  settings: Settings,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  table: Table,
  tag: Tag,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  unplug: Unplug,
  upload: Upload,
  users: Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  waves: Waves,
  wifi: Wifi,
  wind: Wind,
  x: X,
  zap: Zap,
}

export function Icon({ name, size, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) {
    if (import.meta.env.DEV) console.warn(`[Icon] unknown icon "${name}"`)
    return null
  }
  return <Cmp {...(size != null ? { size } : {})} {...rest} />
}
